name: ros2-humble

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Set up ROS
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # SteCache ROS dependencies
      - name: Cache ROS dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ros
            /tmp/rosdep
            /opt/ros/humble
          key: ${{ runner.os }}-ros2-humble-${{ hashFiles('**/package.xml') }}-rosdep
          restore-keys: |
            ${{ runner.os }}-ros2-humble-${{ hashFiles('**/package.xml') }}-
            ${{ runner.os }}-ros2-humble-

      # Step 3: Run ROS CI
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: plotjuggler
          target-ros2-distro: humble
